export const NATIONALITY_OPTIONS = [
  'Omani',
  'Bahraini',
  'Emirati',
  'Kuwaiti',
  'Qatari',
  'Saudi Arabian',
  'Yemeni',
  'Indian',
  'Pakistani',
  'Bangladeshi',
  'Sri Lankan',
  'Nepalese',
  'Filipino',
  'Indonesian',
  'Malaysian',
  'Egyptian',
  'Jordanian',
  'Lebanese',
  'Syrian',
  'Sudanese',
  'Iraqi',
  'Iranian',
  'Palestinian',
  'Ethiopian',
  'Kenyan',
  'Tanzanian',
  'Ugandan',
  'South African',
  'British',
  'American',
  'Canadian',
  'Australian',
  'Other',
] as const;
